create table if not exists public.tracking_links (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  target_url text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  owner_id uuid references auth.users(id) default auth.uid()
);

create table if not exists public.tracking_events (
  id bigint generated by default as identity primary key,
  link_id bigint not null references public.tracking_links(id) on delete cascade,
  created_at timestamptz not null default now(),
  device_name text,
  user_agent text,
  latitude double precision,
  longitude double precision,
  accuracy_m double precision
);

alter table public.tracking_links enable row level security;
alter table public.tracking_events enable row level security;

-- Public tracker needs to find an active link by slug.
create policy "public can read active links"
on public.tracking_links for select
to anon, authenticated
using (active = true);

-- The consent page records an event only after the browser interaction.
create policy "public can insert tracking events"
on public.tracking_events for insert
to anon, authenticated
with check (true);

-- Dashboard owner can see their own events.
create policy "owners read own events"
on public.tracking_events for select
to authenticated
using (
  exists (
    select 1 from public.tracking_links l
    where l.id = tracking_events.link_id
      and l.owner_id = auth.uid()
  )
);

-- Dashboard owner can create links.
create policy "owners create links"
on public.tracking_links for insert
to authenticated
with check (owner_id = auth.uid());

-- Dashboard owner can update/delete their links if you add management UI later.
create policy "owners update links"
on public.tracking_links for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

create policy "owners delete links"
on public.tracking_links for delete
to authenticated
using (owner_id = auth.uid());

create index if not exists tracking_links_slug_idx on public.tracking_links(slug);
create index if not exists tracking_events_link_idx on public.tracking_events(link_id);
create index if not exists tracking_events_created_idx on public.tracking_events(created_at desc);
